services:
    _defaults:
        public: true

    # If you need to access services in a myapp, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with myapp. For example:
    #
    # myapp.App\Service\MyService: '@App\Service\MyService'
